version: "3.8"
services:
    postgres:
        build: ./postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=ecom
        ports:
            - 5432:5432
    cubejs:
        image: cubejs/cube:v0.27.31
        # build: ./
        depends_on: 
            - postgres
        ports:
            - 4001:4000
            - 3000:3000
        environment:
            - CUBEJS_DEV_MODE=true
            - CUBEJS_API_SECRET=jousting_turkeys